# @package _global_

# runs with execution time profiling

defaults:
  - default

trainer:
  max_epochs: 1
  accelerator: gpu
  # profiler: "simple"
  # profiler: "advanced"
  profiler: "pytorch"
  enable_checkpointing: False

data:
  num_workers: 7
